// AUTO-GENERATED by scripts/capture-guide.mjs — do not edit by hand.
// Maps guide image filenames to intrinsic dimensions so <img> tags reserve
// space (no layout shift) without hand-typing sizes.
export const GUIDE_IMAGES: Record<string, { width: number; height: number }> = {
  "learning-01-landing.webp": { width: 780, height: 1688 },
  "learning-02-explore.webp": { width: 780, height: 1688 },
  "learning-03-viewer.webp": { width: 780, height: 1688 },
  "learning-04a-choice.webp": { width: 684, height: 508 },
  "learning-04b-write.webp": { width: 684, height: 348 },
  "learning-04c-blankdrag.webp": { width: 684, height: 424 },
  "learning-05-feedback.webp": { width: 684, height: 1216 },
  "learning-06-askai.webp": { width: 780, height: 1688 },
  "learning-07-personality.webp": { width: 780, height: 1688 },
  "learning-08a-history.webp": { width: 780, height: 1688 },
  "learning-08b-memory.webp": { width: 780, height: 1688 },
  "learning-09-settings.webp": { width: 780, height: 1688 },
};
